[package]
name = "whirlpool-archives"
version = "0.1.0"
edition = "2021"

[features]
default = []
transaction_decimals = []

[dependencies]
serde = "1.0.188"
serde_derive = "1.0.188"
serde_json = { version = "1.0.107", features = ["preserve_order"] }
base64 = "0.21.4"
bigdecimal = "0.4.5"
