[package]
name = "whirlpool-archive-serde"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
base64 = { workspace = true }
bigdecimal = { workspace = true }
