[package]
name = "whirlpool-event"
version = "0.1.0"
edition = "2021"

[dependencies]
whirlpool-archive-serde = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
bigdecimal = { workspace = true }
