[package]
name = "whirlpool-transaction"
version.workspace = true
edition.workspace = true

[dependencies]
whirlpool-archive-serde = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
bigdecimal = { workspace = true }
